import RenderAllModal from "@/Components/Home/Modal/RenderAllModal";
import Footer from "@/Components/Home/Utility/Footer";
import ResponsiveAppBar from "@/Components/Home/Utility/ResponsiveAppBar";
import { UserAuthContexProvider } from "@/Context/UserAuthContext";
import { UseStoreContextProvider } from "@/Context/UseStoreContext";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: "ORG Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://unicons.iconscout.com/release/v4.0.8/css/line.css"
        />
      </head>
      <body className=" bg-ground  text-white" >
        <UseStoreContextProvider>
          <UserAuthContexProvider>
            <RenderAllModal />
            <Toaster position="top-center" reverseOrder={false} />
            {children}
            <Footer/>
          </UserAuthContexProvider>
        </UseStoreContextProvider>{" "}
      </body>
    </html>
  );
}
